apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
  name: myapp
  namespace: ci
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: myapp
  type: LoadBalancer
