apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: nginx
  annotations:
    federation.kubernetes.io/replica-set-preferences: |
        {
            "rebalance": true,
            "clusters": {
                "cluster0": {
                    "minReplicas": 0,
                    "maxReplicas": 15,
                    "weight": 0
                },
                "cluster1": {
                    "minReplicas": 0,
                    "maxReplicas": 15,
                    "weight": 20
                }
            }
        }
spec:
  replicas: 15
  template:
    metadata:
      labels:
        region: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.10
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
